const constants = {
	LOGIN_FACEBOOK_REQUEST: 'LOGIN_FACEBOOK_REQUEST',
	LOGIN_FACEBOOK_SUCCESS: 'LOGIN_FACEBOOK_SUCCESS',
	LOGIN_FACEBOOK_FAILURE: 'LOGIN_FACEBOOK_FAILURE',
	SET_CURRENT_USER: 'SET_CURRENT_USER',
	SHOW_CREATE_RESTAURANT_MODAL: 'SHOW_CREATE_RESTAURANT_MODAL',
	HIDE_CREATE_RESTAURANT_MODAL: 'HIDE_CREATE_RESTAURANT_MODAL',
	GET_RESTAURANTS_REQUEST: 'GET_RESTAURANTS_REQUEST',
	GET_RESTAURANTS_SUCCESS: 'GET_RESTAURANTS_SUCCESS',
	GET_RESTAURANTS_FAILURE: 'GET_RESTAURANTS_FAILURE',
	GET_MENUS_REQUEST: 'GET_MENUS_REQUEST',
	GET_MENUS_SUCCESS: 'GET_MENUS_SUCCESS',
	GET_MENUS_FAILURE: 'GET_MENUS_FAILURE',
	SET_CURRENT_RESTAURANT: 'SET_CURRENT_RESTAURANT',
	SET_CURRENT_MENU: 'SET_CURRENT_MENU',
	SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
	SHOW_CREATE_MENU_MODAL: 'SHOW_CREATE_MENU_MODAL',
	HIDE_CREATE_MENU_MODAL: 'HIDE_CREATE_MENU_MODAL'
}

export default constants