const constants = {
	LOGIN_FACEBOOK_REQUEST: 'LOGIN_FACEBOOK_REQUEST',
	LOGIN_FACEBOOK_SUCCESS: 'LOGIN_FACEBOOK_SUCCESS',
	LOGIN_FACEBOOK_FAILURE: 'LOGIN_FACEBOOK_FAILURE',
	SET_CURRENT_USER: 'SET_CURRENT_USER',
	SHOW_CREATE_RESTAURANT_MODAL: 'SHOW_CREATE_RESTAURANT_MODAL',
	HIDE_CREATE_RESTAURANT_MODAL: 'HIDE_CREATE_RESTAURANT_MODAL',
	GET_RESTAURANTS_REQUEST: 'GET_RESTAURANTS_REQUEST',
	GET_RESTAURANTS_SUCCESS: 'GET_RESTAURANTS_SUCCESS',
	GET_RESTAURANTS_FAILURE: 'GET_RESTAURANTS_FAILURE'
}

export default constants